name: flutterbasestructure
description: A new Flutter application.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #language
  flutter_localizations:
    sdk: flutter
  sprintf: ^6.0.0
  
  #network
  retrofit: ^3.0.1+1
  graphql_flutter: ^5.0.1

  #base
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  intl: ^0.17.0
  flutter_svg_provider: ^1.0.3
  flutter_svg: ^1.1.0
  
  #utils
  logger: ^1.1.0
  pedantic: ^1.11.1
  date_format: ^2.0.6
  connectivity_plus: ^2.0.3
  package_info: ^2.0.2 
  device_info: ^2.0.2 
  permission_handler: ^9.2.0
  url_launcher: ^6.1.2
  file_picker: ^4.6.1

  #ui
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.9
  flutter_statusbarcolor_ns: ^0.4.0
  flutter_spinkit: ^5.1.0
  flutter_easyloading: ^3.0.5
  badges: ^2.0.3
  webview_flutter: ^3.0.4
  pull_to_refresh: ^2.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:  
  build_runner: ^2.0.4 #ns
  retrofit_generator: ^4.0.1
  json_serializable: ^6.0.1
  hive_generator: ^1.1.1
  module_generator:
    path: ./tools/module_generator

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true 

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/languages/
   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
