# dev
app.dev.name=Flutter DEV
app.dev.package=net.vnsilicon.flutter.dev

# staging
app.staging.name=Flutter STAGING
app.staging.package=net.vnsilicon.flutter.staging

# prod
app.prod.name=Flutter Core
app.prod.package=net.vnsilicon.flutter
