# dev
app.dev.name=My Flutter Base DEV
app.dev.package=com.pbh.myflutterbase.dev

# staging
app.staging.name=My Flutter Base STAGING
app.staging.package=com.pbh.myflutterbase.staging

# sandbox
app.sandbox.name=My Flutter Base SANDBOX
app.sandbox.package=com.pbh.myflutterbase.sandbox

# prod
app.prod.name=My Flutter Base
app.prod.package=com.pbh.myflutterbase
