import '../../../common/definitions.dart';

const assetsRes = '''/// This file is automatically generated. 
/// DO NOT EDIT, all your changes would be lost.
/// flutter pub run module_generator:generate_asset
class Assets {
  Assets._();
$contentKey
}
''';
