const assetsRes = '''///This file is automatically generated.
///DO NOT EDIT, all your changes would be lost.
///dart run module_generator:generate_asset <path-to-root-preview-image>

part 'image_assets.dart';
part 'svg_assets.dart';
part 'other_assets.dart';
part 'rive_assets.dart';

class Assets {
  Assets._();

  static ImageAssets get image => ImageAssets();

  static SvgAssets get svg => SvgAssets();

  static RiveAssets get rive => RiveAssets();

  static OtherAssets get other => OtherAssets();
}
''';
