import '../../../common/definations.dart';

const svgAssetsRes = '''///This file is automatically generated.
///DO NOT EDIT, all your changes would be lost.
///dart run module_generator:generate_asset <path-to-root-preview-image>
part of 'assets.dart';

class SvgAssets {
  SvgAssets();$contentKey
}
''';
